### ISSUE TITLE
Can you provide datasets and pre-trained models?

### ISSUE THREAD

**Issue by ChunGaoY** [qianmingduowan/unet-pspnet-unet2d-segment-implement#1]
Hi, thank you for the public code, because my computer configuration is very low, so I cannot successfully train this model. Can you provide datasets and pre-trained models? My email address is 1428681147@qq.com, thank you again.

**Comment by qianmingduowan** [comment]
Data sets Satellite images provided by a company have a confidentiality agreement.  Therefore, I'm sorry I can't provide it to you. I suggest downloading some public data sets.

**Comment by qianmingduowan** [comment]
> Hi, thank you for the public code, because my computer configuration is very low, so I cannot successfully train this model. Can you provide datasets and pre-trained models? My email address is [1428681147@qq.com](mailto:1428681147@qq.com), thank you again.

Data sets Satellite images provided by a company have a confidentiality agreement.  Therefore, I'm sorry I can't provide it to you. I suggest downloading some public data sets.
